development:
  adapter: mysql2
  database: vermeer_development
  username: root
  password: vrosca25022008
  host: localhost
  encoding: utf8

production:
 adapter: mysql2
 database: vermeer_development
 username: root
 password: vrosca25022008
 host: localhost
 encoding: utf8
