development:
  adapter: mysql2
  database: vermeer_development
  username: root
  password:
  host: localhost
  encoding: utf8

production:
 adapter: mysql2
 database: vermeer_development
 username: root
 password:
 host: localhost
 encoding: utf8
